# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # - name: Cache workspace images
  #   init: docker pull gitpod/workspace-full:latest; touch /workspace/.dinit; exit;

  - name: Compile project
    command: |
      curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall; # Install bashbox
      bashbox build --release;
      touch /workspace/.binit;

  - name: Live test dotfiles
    command: |
      printf "\033[3J\033c\033[3J";
      printf 'info: %s\n' "Waiting for the 'init' docker-pull to complete ...";
      until test -e /workspace/.binit; do {
        sleep 0.5;
        continue;
      } done
      source "$HOME/.bashbox/env";

      bashbox live; # `live` is a custom project command defined in `Bashbox.sh`
vscode:
  extensions:
    - mads-hartmann.bash-ide-vscode
    - timonwong.shellcheck

ports:
  - port: 33000
    onOpen: ignore