# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall && exit

vscode:
  extensions:
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
